name: sbgraph

on:
  push:

jobs:

  buid:
    name: Gen data and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run sbgraph
      run : |
        curl -LO https://github.com/mamezou-tech/sbgraph/releases/download/v0.3.0/sbgraph-linux-amd64.tar.gz
        tar xvf sbgraph-linux-amd64.tar.gz
        mkdir ~/bin
        export PATH=$PATH:~/bin
        mv sbgraph ~/bin
        sbgraph init
        sbgraph project -p kondoumh
        sbgraph fetch
        sbgraph aggregate
        sbgraph graph -i=true -a=true -j=true
        sbgraph project -p help-jp
        sbgraph fetch
        sbgraph aggregate
        sbgraph graph -i=true -a=true -j=true
        ls -l _work/kondoumh | wc -l
        ls -l _work/help-jp | wc -l
        rm -r _work/kondoumh
        rm -r _work/help-jp
        mv _work/* public

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Build App
      run: |
        npm install
        npm run build

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.0
      with:
        publish-dir: './dist'
        production-branch: master
        github-token: ${{ secrets.GH_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
